# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Rebuild
        id: rebuild
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: 'https://api.cervidae.com.au/cicd/rest/rebuild'
          method: 'GET'
          timeout: 3000000

      - name: Wait
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'

      - name: Check Service Status
        id: check
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: 'https://api.cervidae.com.au/cicd/rest/check'
          method: 'GET'

      - name: Check Service Status
        run: if [ ${{ steps.check.outputs.response }} -eq 1 ]; then echo "service nominal"; else exit 1; fi

      - name: Get Service Info
        id: info
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: 'https://api.cervidae.com.au/cicd/rest/info'
          method: 'GET'

      - name: Show Response
        run: echo ${{ steps.info.outputs.response }}
